### ISSUE TITLE
Server-Side Request Forgery Vulnerability in NPM Audit

### ISSUE THREAD

**Issue by korajasekar** [smakosh/gatsby-source-dribbble#15]
Getting a high vulnerability warning in NPM audit, because of Axios dependency.
I guess its fixed in 0.21.1. Need to update the dependency.

|    |   |
| ------------- | ------------- |
| High  | Server-Side Request Forgery  |
| Package  | axios  |
| Patched in  | >=0.21.1  |
| Dependency of  | gatsby-source-dribbble  |
| Path  | gatsby-source-dribbble > axios  |

**Comment by smakosh** [comment]
Fixed
